create table if not exists item (
  id  INT generated always as identity,
  label_id int,
  genre_id int,
  author_id int,
  publish_date date,
  archived boolean,
  primary key(id),
  foreign key (label_id) references labels (id),
  foreign key (genre_id) references genre (id),
  foreign key (author_id) references authors (id)
);

CREATE TABLE MUSIC_ALBUM(
  on_spotify boolean NOT NULL,
  id int GENERATED BY DEFAULT AS IDENTITY,
  publish_date date NOT NULL,
  archived boolean
) INHERIT(item);

CREATE TABLE genre(
  id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255)
);


create table Game (
  multiplayer BOOLEAN,
  last_played_at DATE
)

create table Authors (
  id  INT generated always as identity,
  first_name varchar(500),
  last_name varchar(500),
  primary key(id),

  foreign key(id) references item(id)
)


CREATE TABLE books(
  id SERIAL  primary key 
  publish_date DATE,
  publisher VARCHAR(50),
  cover_state VARCHAR(50),
  Item_id INTEGER REFERENCES item(id),
) 

CREATE TABLE labels(
  id SERIAL  primary key 
  title varchar(50),
  color varchar(50)
) 
